### PR TITLE
Disable searching ancestors when looking up constants

### LINKED ISSUE #536: Undefined method cast
_Warning_: Github issues are not an official support channel for Recurly. If you have an urgent request we suggest you contact us through an official channel: support@recurly.com or https://recurly.zendesk.com

**Describe the bug**

We have an `ActiveRecord` class called `Invoice` and for some reason this was sometimes breaking specs. To fix this, I added:
```
elsif type == :Invoice
  Resources::Invoice
```
to `lib/recurly/schema.rb:46` and that got specs passing correctly.

**Expected behavior**
Gem should not be trying to cast the value of an external class.
**Your Environment**
- Which version of this library are you using? - 3.1

### PR DESCRIPTION
**Pull request by douglasmiller**
Resolves #536

The `const_defined?` and `const_get` methods will search the full ancestor tree and will provide a result for the top most matching constant when the `inherit` parameter is true. This causes issues when an application has constants defined on the top level scope that share names with Recurly constants.

The issue was verified to exist using the `bin/pry` script:
```ruby
[1] pry(main)> require 'recurly'
=> true
[2] pry(main)> Recurly::Schema.get_recurly_class(:Invoice)
=> Recurly::Resources::Invoice
[3] pry(main)> class Invoice; end
=> nil
[4] pry(main)> Recurly::Schema.get_recurly_class(:Invoice)
=> Invoice
```

After the change, the same test produces the correct result:
```ruby
[1] pry(main)> require 'recurly'
=> true
[2] pry(main)> Recurly::Schema.get_recurly_class(:Invoice)
=> Recurly::Resources::Invoice
[3] pry(main)> class Invoice; end
=> nil
[4] pry(main)> Recurly::Schema.get_recurly_class(:Invoice)
=> Recurly::Resources::Invoice
```

### CODE REVIEW

File: lib/recurly/schema.rb [hunk 1]
```diff
@@ -42,11 +42,11 @@ def self.get_recurly_class(type)
       raise ArgumentError, "#{type.inspect} must be a symbol but is a #{type.class}" unless type.is_a?(Symbol)
 
       if type == :Address
-        Resources::Address
-      elsif Requests.const_defined?(type)
-        Requests.const_get(type)
-      elsif Recurly::Resources.const_defined?(type)
-        Resources.const_get(type)
+        Recurly::Resources::Address
+      elsif Recurly::Requests.const_defined?(type, false)
```
Comment (bhelx) [inline lib/recurly/schema.rb]: Do we need to do the same to this call? https://github.com/recurly/recurly-client-ruby/blob/65f65171cc2cbb6db99f2ea4c8b327ae12577fcc/lib/recurly/schema/json_parser.rb#L64

Comment (douglasmiller) [reply lib/recurly/schema.rb]: Done

File: lib/recurly/schema/json_parser.rb [hunk 2]
```diff
@@ -61,16 +61,11 @@ def self.recurly_class(type)
...
-            klazz
-          else
-            if Recurly::STRICT_MODE
-              raise ArgumentError, "Could not find Recurly Resource responsible for key #{type}"
-            else
-              nil
-            end
+        if Resources.const_defined?(type_camelized, false)
+          Resources.const_get(type_camelized, false)
+        else
```
Comment (bhelx) [inline lib/recurly/schema/json_parser.rb]: What do you think about making this `elsif Recurly::STRICT_MODE` then it would not have an else clause (returning nil)?

**Comment by bhelx** [comment]
👍
